version: '3.8'

services:
  apps:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "
                    chmod +x entrypoint.sh &&
                    sh entrypoint.sh"
    volumes:
      - ./media:/media   # <--- локальная папка на хосте
      - ./static:/static
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  # front:
  #   build: ./frontend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://94.198.217.222
  #   ports:
  #     - '3000:80'

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - apps



volumes:
  postgres_data:
  redis-data:
  
