version: '3.8'

services:
  apps:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "
                    chmod +x entrypoint.sh &&
                    sh entrypoint.sh"
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  front:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://94.198.217.222/api
    ports:
      - 3000:80


volumes:
  postgres_data:
  redis-data:
  media:
  static:
  
